### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by github-liyan** [jfgrim/redis4AppenderLog4j#1]
java.lang.ClassNotFoundException: client.redis.log4jAppender.RedisAppender

Spark on yarn Run spak job，I want  write logs to redis，and I added the pom.xml 
【<dependency>
            <groupId>com.github.jfgrim</groupId>
            <artifactId>redis4AppenderLog4j</artifactId>
            <version>1.0.0</version>
        </dependency>】

 but erroe: ClassNotFoundException when Spark job run on yarn cluster.

error message:
【log4j:ERROR Could not instantiate class [client.redis.log4jAppender.RedisAppender].
java.lang.ClassNotFoundException: client.redis.log4jAppender.RedisAppender
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.log4j.helpers.Loader.loadClass(Loader.java:198)
	at org.apache.log4j.helpers.OptionConverter.instantiateByClassName(OptionConverter.java:327)
	at org.apache.log4j.helpers.OptionConverter.instantiateByKey(OptionConverter.java:124)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:785)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.parseCatsAndRenderers(PropertyConfigurator.java:672)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:516)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.apache.spark.Logging$class.initializeLogging(Logging.scala:121)
	at org.apache.spark.Logging$class.initializeIfNecessary(Logging.scala:106)
	at org.apache.spark.Logging$class.log(Logging.scala:50)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.log(CoarseGrainedExecutorBackend.scala:138)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:149)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:253)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)】

**Comment by jfgrim** [comment]
Hi Liyan,
can i see your implementation of your log4j (in log4j.xml or equivalent) ?  
Redis4AppenderLog4j 's code is very simply. 
For its implementation, you can inspire log4j from the injectLog4jToRedis project: https://github.com/jfgrim/injectLog4jToRedis/blob/master/src/main/resources/log4j-inject.xml

**Comment by github-liyan** [comment]
how to collect spark on yarn cluster mode log

**Comment by jfgrim** [comment]
Hi Liyan,
You find configuration's file for Loj4j in this document : [https://mapr.com/blog/how-log-apache-spark/](https://mapr.com/blog/how-log-apache-spark/)
Add this : (change your server's IP and port, password for redis's user)
log4j.rootLogger=DEBUG, redis
log4j.appender.redis=RedisAppender
log4j.appender.redis.layout=…
log4j.appender.redis.hosts=localhost:6379,10.10.3.3:7000
log4j.appender.redis.password=password
log4j.appender.redis.mode=list
log4j.appender.redis.key=key
log4j.appender.redis.period=500
log4j.appender.redis.batchSize=100
log4j.appender.redis.purgeOnFailure=true
log4j.appender.redis.alwaysBatch=true
log4j.appender.redis.daemonThread=true

You can find in your pom.xml this : 
`<dependency>
	<groupId>com.github.jfgrim</groupId>
	<artifactId>redis4AppenderLog4j</artifactId>
	<version>1.0.0</version>
</dependency>
`
